- name: Ensure influxdb directories exist
  file:
    path: "/home/{{ grafana_user }}/appdata/grafana-monitoring/influxdb"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0775
  tags: [ 'directories' ]