- name: Ensure prometheus directories exist
  file:
    path: "/home/{{ grafana_user }}/appdata/grafana-monitoring/{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0775
  loop:
    - 'prometheus'
    - 'prometheus/config'

- name: Ensure prometheus configuration file exists
  template:
    src: roles/grafana/templates/prometheus.yml
    dest: "/home/{{ grafana_user }}/appdata/grafana-monitoring/prometheus/config/prometheus.yml"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0664
