- name: Ensure telegraf directories exist
  file:
    path: "/home/{{ grafana_user }}/appdata/grafana-monitoring/telegraf"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0775
  tags: [ 'directories' ]

- name: Ensure telegraf configuration file exists
  template:
    src: roles/grafana/templates/telegraf.conf
    dest: "/home/{{ grafana_user }}/appdata/grafana-monitoring/telegraf/telegraf.conf"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0664
  tags: [ 'telegraf' ]