- name: Update APT package manager repositories
  apt:
    update_cache: yes

- name: Install Python and python3-pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Docker dependencies
  apt:
    name: ['ca-certificates', 'curl']
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    state: present
    filename: docker

- name: Update APT package manager repositories (again)
  apt:
    update_cache: yes

- name: Install latest versions
  apt:
    name: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    state: latest

- name: Run Docker hello-world
  command: docker run hello-world
  register: hello_world_output
  changed_when: false

- name: Check hello-world output
  assert:
    that: "'Hello from Docker!' in hello_world_output.stdout"
    fail_msg: "Docker hello-world did not run correctly"