- name: Ensure torrents directory exists
  file:
    path: "/home/{{ arr_stack_user }}/data/torrents"
    state: directory
    owner: "{{ arr_stack_user }}"
    group: "{{ arr_stack_group }}"
    mode: 0775
  tags: [ 'torrents', 'directories' ]

- name: Ensure torrents subdirectories exist
  file:
    path: "/home/{{ arr_stack_user }}/data/torrents/{{ item }}"
    state: directory
    owner: "{{ arr_stack_user }}"
    group: "{{ arr_stack_group }}"
    mode: 0775
  loop: "{{ arr_stack_subdirectories }}"
  tags: [ 'torrents', 'directories' ]
